services:
  angular-ui-web:
    build: .
    container_name: angular-ui-web
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ../certs:/etc/nginx/certs:ro
    networks:
      identity-net:
        ipv4_address: 10.5.0.17
networks:
  identity-net:
    name: identity-net
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
